name: Deploy to GCP

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
            echo "SERVICE_NAME=opsnav-web-service" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "ENV=development" >> $GITHUB_ENV
            echo "SERVICE_NAME=opsnav-web-service-dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON_PROD }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: melodic-keyword-461611-s9

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.IMAGE_TAG }} \
            --build-arg ENV=${{ env.ENV }} \
            -f Dockerfiles/Dockerfile .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.IMAGE_TAG }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.IMAGE_TAG }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 80
