name: Deploy to GCP

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON_PROD }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: melodic-keyword-461611-s9

      - name: Set Environment Variables
        id: env
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "MODE=production" >> $GITHUB_ENV
            echo "SERVICE_SUFFIX=prod" >> $GITHUB_ENV
          elif [ "$GITHUB_REF_NAME" = "development" ]; then
            echo "MODE=development" >> $GITHUB_ENV
            echo "SERVICE_SUFFIX=dev" >> $GITHUB_ENV
          fi

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg MODE=${{ env.MODE }} \
            -t us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.SERVICE_SUFFIX }} \
            -f Dockerfiles/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.SERVICE_SUFFIX }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy opsnav-web-service-${{ env.SERVICE_SUFFIX }} \
            --image us-central1-docker.pkg.dev/melodic-keyword-461611-s9/opsnav-web-repo/opsnav-web-image:${{ env.SERVICE_SUFFIX }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 80 \
            --set-env-vars=VITE_API_BASE_URL=${{ env.MODE == 'production' && 'https://opsnav-app-service-871399330172.us-central1.run.app' || 'https://opsnav-app-service-dev-871399330172.us-central1.run.app' }}